### PR TITLE
Fail on const enums

### LINKED ISSUE #35: Support const enums
Possibly by just failing to translate them if there's no reasonable equivalent in Dart.

### PR DESCRIPTION
**Pull request by chalin**
Fixes #35.

### CODE REVIEW

File: main.ts [hunk 1]
```diff
@@ -414,6 +414,10 @@ class Translator {
 
       case ts.SyntaxKind.EnumDeclaration:
         var decl = <ts.EnumDeclaration>node;
+        // The only legal modifier for an enum decl is const.
```
Comment (mprobst) [inline main.ts]: Could you be explicit about this containing const? It might change in the future, and it's also more readable. I think "export enum Foo" might also be a thing.

Comment (chalin) [inline main.ts]: Done.
